# Generated by Django 3.2.23 on 2023-11-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(default=True, help_text='trạng thái'),
        ),
    ]
